# Generated by Django 5.1.4 on 2026-02-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas_app", "0002_servicio_venta_origen_cotizacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="observaciones",
            field=models.TextField(blank=True),
        ),
    ]
