# Generated by Django 5.1.4 on 2026-01-20 18:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_venta", models.DateField(default=django.utils.timezone.now)),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PARCIAL", "Parcial"),
                            ("PAGADA", "Pagada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                ("fecha_pago_total", models.DateField(blank=True, null=True)),
                ("fecha_inicio_garantia", models.DateField(blank=True, null=True)),
                ("fecha_fin_garantia", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ventas",
                        to="cotizaciones_app.cliente",
                    ),
                ),
                (
                    "cotizacion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venta",
                        to="cotizaciones_app.cotizacion",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_venta", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PagoVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("TRANSFERENCIA", "Transferencia"),
                            ("EFECTIVO", "Efectivo"),
                            ("TARJETA", "Tarjeta"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("referencia", models.CharField(blank=True, max_length=100, null=True)),
                ("observacion", models.TextField(blank=True, null=True)),
                (
                    "correlativo_comprobante",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="cotizaciones_app.venta",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
    ]
