# Generated by Django 5.1.4 on 2026-02-11 20:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones_app", "0002_venta_pagoventa"),
    ]

    operations = [
        migrations.AddField(
            model_name="cotizacion",
            name="descuento_monto",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="descuento_porcentaje",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="iva_porcentaje",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("12.00"), max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="precios_sin_iva",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="subtotal",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="total",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="total_descuento",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="total_iva",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=Decimal("0.00"), max_digits=12, null=True
            ),
        ),
    ]
