# Generated by Django 5.1.4 on 2026-02-12 14:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cotizaciones_app", "0003_cotizacion_descuento_monto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cotizacion",
            name="precios_sin_iva",
        ),
        migrations.RemoveField(
            model_name="cotizacion",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="cotizacion",
            name="total",
        ),
        migrations.RemoveField(
            model_name="cotizacion",
            name="total_descuento",
        ),
        migrations.RemoveField(
            model_name="cotizacion",
            name="total_iva",
        ),
        migrations.AddField(
            model_name="cotizacion",
            name="iva_activo",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="descuento_monto",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="descuento_porcentaje",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="cotizacion",
            name="iva_porcentaje",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("12.00"), max_digits=5
            ),
        ),
    ]
