# Generated by Django 5.1.4 on 2026-02-11 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventas_app", "0003_venta_observaciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="venta",
            name="titulo",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
